# Form implementation generated from reading ui file '.\Templates\calendarWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventanaCalendario(object):
    def setupUi(self, ventanaCalendario):
        ventanaCalendario.setObjectName("ventanaCalendario")
        ventanaCalendario.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        ventanaCalendario.resize(400, 300)
        ventanaCalendario.setMinimumSize(QtCore.QSize(400, 300))
        ventanaCalendario.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Templates\\../img/calendario.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventanaCalendario.setWindowIcon(icon)
        self.calendar = QtWidgets.QCalendarWidget(parent=ventanaCalendario)
        self.calendar.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.calendar.setMinimumSize(QtCore.QSize(400, 300))
        self.calendar.setMaximumSize(QtCore.QSize(400, 300))
        self.calendar.setObjectName("calendar")

        self.retranslateUi(ventanaCalendario)
        QtCore.QMetaObject.connectSlotsByName(ventanaCalendario)

    def retranslateUi(self, ventanaCalendario):
        _translate = QtCore.QCoreApplication.translate
        ventanaCalendario.setWindowTitle(_translate("ventanaCalendario", "Elige una fecha de alta"))
