# Form implementation generated from reading ui file '.\Templates\dlgAcercaDe.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAcercaDe(object):
    def setupUi(self, dlgAcercaDe):
        dlgAcercaDe.setObjectName("dlgAcercaDe")
        dlgAcercaDe.resize(400, 230)
        dlgAcercaDe.setMinimumSize(QtCore.QSize(400, 230))
        dlgAcercaDe.setMaximumSize(QtCore.QSize(400, 230))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Templates\\../img/acercaDe.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgAcercaDe.setWindowIcon(icon)
        self.btnCerrarAcercaDe = QtWidgets.QPushButton(parent=dlgAcercaDe)
        self.btnCerrarAcercaDe.setGeometry(QtCore.QRect(310, 190, 75, 23))
        self.btnCerrarAcercaDe.setObjectName("btnCerrarAcercaDe")
        self.frame = QtWidgets.QFrame(parent=dlgAcercaDe)
        self.frame.setGeometry(QtCore.QRect(20, 20, 361, 151))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setObjectName("frame")
        self.lblAcercaDeImg = QtWidgets.QLabel(parent=self.frame)
        self.lblAcercaDeImg.setGeometry(QtCore.QRect(10, -40, 131, 181))
        self.lblAcercaDeImg.setText("")
        self.lblAcercaDeImg.setPixmap(QtGui.QPixmap(".\\Templates\\../img/logo.ico"))
        self.lblAcercaDeImg.setObjectName("lblAcercaDeImg")
        self.lblAcercaDeTitulo = QtWidgets.QLabel(parent=self.frame)
        self.lblAcercaDeTitulo.setGeometry(QtCore.QRect(160, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblAcercaDeTitulo.setFont(font)
        self.lblAcercaDeTitulo.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lblAcercaDeTitulo.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lblAcercaDeTitulo.setObjectName("lblAcercaDeTitulo")
        self.lblAcercaDeDescripcion = QtWidgets.QLabel(parent=self.frame)
        self.lblAcercaDeDescripcion.setGeometry(QtCore.QRect(170, 60, 171, 16))
        self.lblAcercaDeDescripcion.setObjectName("lblAcercaDeDescripcion")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(240, 80, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(170, 100, 171, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(250, 120, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(dlgAcercaDe)
        QtCore.QMetaObject.connectSlotsByName(dlgAcercaDe)

    def retranslateUi(self, dlgAcercaDe):
        _translate = QtCore.QCoreApplication.translate
        dlgAcercaDe.setWindowTitle(_translate("dlgAcercaDe", "Acerca de CarTeis"))
        self.btnCerrarAcercaDe.setText(_translate("dlgAcercaDe", "Cerrar"))
        self.lblAcercaDeTitulo.setText(_translate("dlgAcercaDe", "CarTeis"))
        self.lblAcercaDeDescripcion.setText(_translate("dlgAcercaDe", "Servicio de transporte personal"))
        self.label.setText(_translate("dlgAcercaDe", "Version 0.1.0"))
        self.label_2.setText(_translate("dlgAcercaDe", "Hugo Ruiz Pozo"))
        self.label_3.setText(_translate("dlgAcercaDe", "OpenSource"))
