# Form implementation generated from reading ui file '.\Templates\dlgAltaNueva.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAltaNueva(object):
    def setupUi(self, dlgAltaNueva):
        dlgAltaNueva.setObjectName("dlgAltaNueva")
        dlgAltaNueva.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dlgAltaNueva.resize(400, 86)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Templates\\../img/logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgAltaNueva.setWindowIcon(icon)
        self.lblVolverAlta = QtWidgets.QLabel(parent=dlgAltaNueva)
        self.lblVolverAlta.setGeometry(QtCore.QRect(40, 5, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblVolverAlta.setFont(font)
        self.lblVolverAlta.setStyleSheet("")
        self.lblVolverAlta.setObjectName("lblVolverAlta")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=dlgAltaNueva)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 40, 231, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAltaNueva = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnAltaNueva.setObjectName("btnAltaNueva")
        self.horizontalLayout.addWidget(self.btnAltaNueva)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnAltaCerrar = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btnAltaCerrar.setObjectName("btnAltaCerrar")
        self.horizontalLayout.addWidget(self.btnAltaCerrar)

        self.retranslateUi(dlgAltaNueva)
        QtCore.QMetaObject.connectSlotsByName(dlgAltaNueva)

    def retranslateUi(self, dlgAltaNueva):
        _translate = QtCore.QCoreApplication.translate
        dlgAltaNueva.setWindowTitle(_translate("dlgAltaNueva", "Alta nueva"))
        self.lblVolverAlta.setText(_translate("dlgAltaNueva", "¿Quieres volver a dar de alta el conductor?"))
        self.btnAltaNueva.setText(_translate("dlgAltaNueva", "Alta nueva"))
        self.btnAltaCerrar.setText(_translate("dlgAltaNueva", "Cerrar"))
