# Form implementation generated from reading ui file '.\Templates\dlgSalir.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgSalir(object):
    def setupUi(self, dlgSalir):
        dlgSalir.setObjectName("dlgSalir")
        dlgSalir.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dlgSalir.resize(300, 80)
        dlgSalir.setMinimumSize(QtCore.QSize(300, 80))
        dlgSalir.setMaximumSize(QtCore.QSize(300, 80))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Templates\\../img/salir.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgSalir.setWindowIcon(icon)
        self.btnSalirCancelar = QtWidgets.QPushButton(parent=dlgSalir)
        self.btnSalirCancelar.setGeometry(QtCore.QRect(120, 50, 75, 23))
        self.btnSalirCancelar.setObjectName("btnSalirCancelar")
        self.btnSalirSalir = QtWidgets.QPushButton(parent=dlgSalir)
        self.btnSalirSalir.setGeometry(QtCore.QRect(210, 50, 75, 23))
        self.btnSalirSalir.setObjectName("btnSalirSalir")
        self.lblSalir = QtWidgets.QLabel(parent=dlgSalir)
        self.lblSalir.setGeometry(QtCore.QRect(20, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblSalir.setFont(font)
        self.lblSalir.setObjectName("lblSalir")

        self.retranslateUi(dlgSalir)
        QtCore.QMetaObject.connectSlotsByName(dlgSalir)

    def retranslateUi(self, dlgSalir):
        _translate = QtCore.QCoreApplication.translate
        dlgSalir.setWindowTitle(_translate("dlgSalir", "Salir"))
        self.btnSalirCancelar.setText(_translate("dlgSalir", "Cancelar"))
        self.btnSalirSalir.setText(_translate("dlgSalir", "Salir"))
        self.lblSalir.setText(_translate("dlgSalir", "¿Deseas salir de CarTeis?"))
